
clear;
total_scores = {};
algoIds = [8 9 10 11 12 13 14 15];
for j = 1:length(algoIds)
    total_scores{j} = [];
end
% reslistic
% fs = {
%     'res_car', 'res_motor'
%     };
% realistic + house
% fs = {
%     'res_car',...
%     'res_motor',...
%     'res_house_10vs30',...
%     'res_house_20vs30',...
%     'res_house_30vs30',...
%     }
% random 
% fs = {
%     'res_random'
%     };
% synthetic 10 inliers
% fs = {
%     'out_000def',...
%     'out_001def',...
%     'out_001def_11scale',...
%     'out_001def_101scale',...
%     'out_003def_15scale',...
%     };
% synthetic >= 20inliers
% fs = {
%     'def_20inlier',...
%     'def_30inlier',...
%     'def_40inlier',...
%     'out_000def_20inlier',...
%     'out_001def_20inlier',...
%     'out_001def_11scale_20inlier',...
%     'out_001def_101scale_20inlier',...
%     'out_003def_15scale_20inlier',...
%     'out_01def_20inlier',...
%     'out_02def_20inlier',...
%     };
% synthetic
% fs = {
%     'def_20inlier',...
%     'def_30inlier',...
%     'def_40inlier',...
%     'out_000def',...
%     'out_001def',...
%     'out_001def_11scale',...
%     'out_001def_101scale',...
%     'out_003def_15scale',...
%     'out_000def_20inlier',...
%     'out_001def_20inlier',...
%     'out_001def_11scale_20inlier',...
%     'out_001def_101scale_20inlier',...
%     'out_003def_15scale_20inlier',...
%     'out_01def_20inlier',...
%     'out_02def_20inlier',...
%     };
% ALL
% fs = {
%     'res_house_10vs30',...
%     'res_house_20vs30',...
%     'res_house_30vs30',...
%     'def_20inlier',...
%     'def_30inlier',...
%     'def_40inlier',...
%     'out_000def',...
%     'out_001def',...
%     'out_001def_11scale',...
%     'out_001def_101scale',...
%     'out_003def_15scale',...
%     'out_000def_20inlier',...
%     'out_001def_20inlier',...
%     'out_001def_11scale_20inlier',...
%     'out_001def_101scale_20inlier',...
%     'out_003def_15scale_20inlier',...
%     'out_01def_20inlier',...
%     'out_02def_20inlier',...
%     'res_car',...
%     'res_motor',...
%     'res_random'
%     };
% Willow Object Class
fs = {
    'res_winebottle_0_0_0',...
    'res_duck_0_0_0',...
    'res_face_0_0_0'
    };

for i = 1:length(fs)
    load(fs{i});
    for j = 1:length(algoIds)
        total_scores{j} = [total_scores{j}; Scores{algoIds(j)}];
    end
end

% our statistics
stats = [];

for j = 1:length(algoIds)
    a = total_scores{j};
    res = [];
    
    % # importance of alpha=0 phase
    res(1) = length(find(a(:, 1) == 1));
    res(2) = length(find(a(:, 2) == a(:, 3)));
    res(3) = length(find(a(:, 2) > a(:, 3)));
    res(4) = length(find(a(:, 2) < a(:, 3)));
    
    % # importance of alpha>0 phase
    res(5) = length(find(a(:, 3) < a(:, 6)));
    res(6) = length(find(a(:, 7) < a(:, 8)));
    res(7) = length(find(a(:, 6) < a(:, 9)));
    res(8) = length(find(a(:, 3) < a(:, 9)));
    res(9) = length(find(a(:, 3) > a(:, 9)));
    res(10) = length(find(a(:, 3) == a(:, 9)));
    stats = [stats; res];
end
